
apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "flame-db-01"
spec:
  defaults:
    replicasUseFQDN: "no"
    distributedDDL:
      profile: default
    templates:
      podTemplate: pod-template
      dataVolumeClaimTemplate: data-volume-template
  configuration:
    users:
      dbuser/password: simplePassword
      dbuser/profile: default
      dbuser/quota: default
      dbuser/networks/ip: "::/0"
    zookeeper:
      nodes:
        - host: zookeeper
          port: 2181
    clusters:
      - name: "flame-db"
        layout:
          shardsCount: 3
          replicasCount: 2
  templates:
    podTemplates:
      - name: pod-template
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:22.10
    volumeClaimTemplates:
      - name: data-volume-template
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
